"""baseline_and_server_info

Revision ID: 8eed2e88925f
Revises: 
Create Date: 2026-04-23 14:12:59.239326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eed2e88925f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_server_information', 'listindex',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partner_server_information', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('partners', sa.Column('server_information_id', sa.String(length=50), nullable=True))
    op.add_column('partners', sa.Column('server_information_detail', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'partners', 'partner_server_information', ['server_information_id'], ['server_information_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='foreignkey')
    op.drop_column('partners', 'server_information_detail')
    op.drop_column('partners', 'server_information_id')
    op.alter_column('partner_server_information', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('partner_server_information', 'listindex',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
